name: 'Hello World'
description: 'Greet the caller'
inputs:
  the-caller:
    description: 'Who is there'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
runs:
  using: "composite"
  steps:
    - id: greet
      run: echo Hello ${{ inputs.the-caller }}.
      shell: bash
    - id: random-number-generator
      run: echo "RANDOM_ID=$(echo $RANDOM)" >> $GITHUB_ENV
      shell: bash
    - id: set-output
      run: |
        RANDOM_NUMBER=$(echo $RANDOM_ID)
        echo "RANDOM_NUMBER=$RANDOM_NUMBER" >> $GITHUB_ENV
        echo "::set-output name=random-number::$RANDOM_NUMBER"
      shell: bash
