name: 'Hello World'
description: 'Greet the caller'
inputs:
  the-caller:
    description: 'Who is there'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
runs:
  using: "composite"
  steps:
    - id: greet
      run: echo Hello ${{ inputs.the-caller }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - id: set-output
      run: echo "::set-output name=random-number::${{ steps.random-number-generator.outputs.random-id }}"
      shell: bash
